language: python

python:
  - "2.7"

install: "pip install -r requirements.txt"

before_script:
  - cp jucy/local_settings.sample jucy/local_settings.py
  - python manage.py migrate

script:
  - python manage.py test
